"""initial_schemas

Revision ID: 7d4406e275ed
Revises: None
Create Date: 2026-09-22 01:42:02.282621

"""
# ruff: noqa: F401
from typing import Sequence

from alembic import op
import sqlalchemy as sa

# auto-generated imports


# revision identifiers, used by Alembic.
revision: str = '7d4406e275ed'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('party_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('party_type', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('party_id')
    )
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parties_display_name'), ['display_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_phone'), ['phone'], unique=False)

    op.create_table('permissions',
    sa.Column('permission_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('permission_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('permission_code')
    )
    op.create_table('products',
    sa.Column('product_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_code')
    )
    op.create_table('warehouses',
    sa.Column('warehouse_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('warehouse_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('warehouse_id'),
    sa.UniqueConstraint('warehouse_code')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.party_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('customer_code')
    )
    op.create_table('locations',
    sa.Column('location_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_location_id', sa.BigInteger(), nullable=True),
    sa.Column('location_code', sa.String(length=50), nullable=False),
    sa.Column('location_name', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('location_type', sa.String(length=30), nullable=False),
    sa.Column('location_purpose', sa.String(length=30), nullable=False),
    sa.Column('can_store_inventory', sa.Boolean(), nullable=False),
    sa.Column('max_weight_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('parent_location_id IS NULL OR parent_location_id != location_id', name='chk_location_parent_not_self'),
    sa.ForeignKeyConstraint(['parent_location_id'], ['locations.location_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('warehouse_id', 'location_code', name='uq_location_warehouse_code')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_parent_location_id'), ['parent_location_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['parties.party_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('supplier_id'),
    sa.UniqueConstraint('supplier_code')
    )
    op.create_table('user_accounts',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('party_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.party_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('party_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('inventories',
    sa.Column('inventory_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('last_counted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_on_hand >= 0', name='chk_inventory_qoh_non_negative'),
    sa.CheckConstraint('reserved_quantity <= quantity_on_hand', name='chk_inventory_reserved_lte_qoh'),
    sa.CheckConstraint('reserved_quantity >= 0', name='chk_inventory_reserved_non_negative'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('inventory_id'),
    sa.UniqueConstraint('location_id', 'product_id', name='uq_inventory_location_product')
    )
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventories_product_id'), ['product_id'], unique=False)

    op.create_table('inventory_movements',
    sa.Column('movement_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('reference_code', sa.String(length=100), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('from_location_id', sa.BigInteger(), nullable=True),
    sa.Column('to_location_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_location_id IS NOT NULL OR to_location_id IS NOT NULL', name='chk_movement_location_present'),
    sa.CheckConstraint('quantity > 0', name='chk_movement_quantity_positive'),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.location_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['performed_by'], ['user_accounts.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.location_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('movement_id')
    )
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movements_from_location_id'), ['from_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_reference_code'), ['reference_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_to_location_id'), ['to_location_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['user_accounts.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movements_to_location_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_reference_code'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_from_location_id'))

    op.drop_table('inventory_movements')
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventories_product_id'))

    op.drop_table('inventories')
    op.drop_table('user_accounts')
    op.drop_table('suppliers')
    op.drop_table('role_permissions')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_parent_location_id'))

    op.drop_table('locations')
    op.drop_table('customers')
    op.drop_table('warehouses')
    op.drop_table('roles')
    op.drop_table('products')
    op.drop_table('permissions')
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parties_phone'))
        batch_op.drop_index(batch_op.f('ix_parties_email'))
        batch_op.drop_index(batch_op.f('ix_parties_display_name'))

    op.drop_table('parties')
    # ### end Alembic commands ###
