CREATE TABLE parties (
    party_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_type VARCHAR(20) DEFAULT 'PERSON' NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    email VARCHAR(255),
    address TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE suppliers (
    supplier_id BIGINT REFERENCES parties(party_id) PRIMARY KEY,
    supplier_code VARCHAR(50) UNIQUE NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE user_accounts (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id BIGINT UNIQUE REFERENCES parties(party_id),
    username VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE warehouses (
    warehouse_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_code VARCHAR(50) UNIQUE NOT NULL,
    warehouse_name VARCHAR(100) NOT NULL,
    address TEXT,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE locations (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT REFERENCES warehouses(warehouse_id),
    parent_location_id BIGINT REFERENCES locations(location_id),
    location_code VARCHAR(50) NOT NULL,
    location_name VARCHAR(100) NOT NULL,
    barcode VARCHAR(100) UNIQUE,
    location_type VARCHAR(30) NOT NULL,
    can_store_inventory BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(50) UNIQUE NOT NULL,
    barcode VARCHAR(100) UNIQUE,
    name VARCHAR(255) NOT NULL,
    unit VARCHAR(30) DEFAULT 'item',
    price NUMERIC(12, 2) DEFAULT 0,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE inventories (
    inventory_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT REFERENCES locations(location_id),
    product_id BIGINT REFERENCES products(product_id),
    quantity_on_hand NUMERIC(18, 4) DEFAULT 0,
    reserved_quantity NUMERIC(18, 4) DEFAULT 0,
    last_counted_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE inventory_movements (
    movement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_type VARCHAR(30) NOT NULL,
    reference_code VARCHAR(100),
    product_id BIGINT REFERENCES products(product_id),
    from_location_id BIGINT REFERENCES locations(location_id),
    to_location_id BIGINT REFERENCES locations(location_id),
    quantity NUMERIC(18, 4) NOT NULL,
    note TEXT,
    performed_by BIGINT REFERENCES user_accounts(user_id),
    occurred_at TIMESTAMP
);

CREATE TABLE equipment_types (
    equipment_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_code VARCHAR(50) UNIQUE NOT NULL,
    type_name VARCHAR(100) NOT NULL,
    manufacturer VARCHAR(100),
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE equipment (
    equipment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_code VARCHAR(50) UNIQUE NOT NULL,
    equipment_name VARCHAR(255) NOT NULL,
    equipment_type_id BIGINT REFERENCES equipment_types(equipment_type_id),
    serial_number VARCHAR(100) UNIQUE,
    location_id BIGINT REFERENCES locations(location_id),
    supplier_id BIGINT REFERENCES suppliers(supplier_id),
    status VARCHAR(30) DEFAULT 'OPERATIONAL',
    purchase_date DATE,
    warranty_expiry DATE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE maintenance_requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_code VARCHAR(50) UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    equipment_id BIGINT REFERENCES equipment(equipment_id),
    reported_by BIGINT REFERENCES user_accounts(user_id),
    priority VARCHAR(30) DEFAULT 'MEDIUM',
    status VARCHAR(30) DEFAULT 'DRAFT', -- DRAFT -> SUBMITTED -> APPROVED/REJECTED
    problem_description TEXT NOT NULL,
    reviewed_by BIGINT REFERENCES user_accounts(user_id),
    reviewed_at TIMESTAMP,
    review_note TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE work_orders (
    work_order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_code VARCHAR(50) UNIQUE NOT NULL,
    request_id BIGINT UNIQUE REFERENCES maintenance_requests(request_id),
    -- equipment_id truy vết qua request_id -> maintenance_requests để tránh diamond relationship
    supervisor_id BIGINT REFERENCES user_accounts(user_id),
    lead_technician_id BIGINT REFERENCES user_accounts(user_id),
    priority VARCHAR(30) DEFAULT 'MEDIUM',
    maintenance_type VARCHAR(30) DEFAULT 'CORRECTIVE',
    status VARCHAR(30) DEFAULT 'ASSIGNED',
    root_cause TEXT,
    repair_action TEXT,
    test_result TEXT,
    acceptance_result VARCHAR(30),
    accepted_by BIGINT REFERENCES user_accounts(user_id),
    accepted_at TIMESTAMP,
    acceptance_note TEXT,
    planned_start_at TIMESTAMP,
    planned_end_at TIMESTAMP,
    actual_start_at TIMESTAMP,
    actual_end_at TIMESTAMP,
    downtime_start TIMESTAMP,
    downtime_end TIMESTAMP,
    closed_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE work_order_tasks (
    task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT REFERENCES work_orders(work_order_id),
    task_order INT DEFAULT 1,
    task_name VARCHAR(255) NOT NULL,
    description TEXT,
    assigned_to BIGINT REFERENCES user_accounts(user_id),
    estimated_hours NUMERIC(6, 2),
    status VARCHAR(30) DEFAULT 'PENDING',
    started_at TIMESTAMP,
    completed_at TIMESTAMP
);

CREATE TABLE work_order_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT REFERENCES work_orders(work_order_id),
    task_id BIGINT REFERENCES work_order_tasks(task_id),
    technician_id BIGINT REFERENCES user_accounts(user_id),
    activity_type VARCHAR(50) NOT NULL,
    labor_hours NUMERIC(6, 2) NOT NULL,
    work_description TEXT,
    logged_at TIMESTAMP
);

CREATE TABLE work_order_materials (
    work_order_material_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT REFERENCES work_orders(work_order_id),
    product_id BIGINT REFERENCES products(product_id),
    -- location_id lược bỏ vì xuất nhập kho thực tế quản lý qua inventory_movements
    required_quantity NUMERIC(18, 4) NOT NULL,
    reserved_quantity NUMERIC(18, 4) DEFAULT 0,
    issued_quantity NUMERIC(18, 4) DEFAULT 0,
    status VARCHAR(30) DEFAULT 'PENDING',
    note TEXT,
    created_at TIMESTAMP
);

CREATE TABLE purchase_requests (
    purchase_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_code VARCHAR(50) UNIQUE NOT NULL,
    work_order_id BIGINT REFERENCES work_orders(work_order_id),
    requested_by BIGINT REFERENCES user_accounts(user_id),
    status VARCHAR(30) DEFAULT 'DRAFT',
    total_estimated_amount NUMERIC(14, 2) DEFAULT 0,
    requested_at TIMESTAMP,
    created_at TIMESTAMP
);

CREATE TABLE purchase_request_items (
    purchase_request_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_request_id BIGINT REFERENCES purchase_requests(purchase_request_id),
    product_id BIGINT REFERENCES products(product_id),
    requested_quantity NUMERIC(18, 4) NOT NULL,
    estimated_unit_price NUMERIC(12, 2) DEFAULT 0,
    required_date DATE,
    status VARCHAR(30) DEFAULT 'PENDING'
);

CREATE TABLE purchase_approvals (
    approval_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_request_id BIGINT REFERENCES purchase_requests(purchase_request_id),
    approver_id BIGINT REFERENCES user_accounts(user_id),
    step_order INT NOT NULL,
    approver_role VARCHAR(30) NOT NULL,
    status VARCHAR(30) DEFAULT 'PENDING',
    comment TEXT,
    acted_at TIMESTAMP
);

CREATE TABLE purchase_orders (
    purchase_order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_code VARCHAR(50) UNIQUE NOT NULL,
    purchase_request_id BIGINT REFERENCES purchase_requests(purchase_request_id),
    supplier_id BIGINT REFERENCES suppliers(supplier_id),
    warehouse_id BIGINT REFERENCES warehouses(warehouse_id),
    status VARCHAR(30) DEFAULT 'ISSUED',
    order_date DATE NOT NULL,
    expected_delivery_date DATE,
    total_amount NUMERIC(14, 2) DEFAULT 0,
    created_by BIGINT REFERENCES user_accounts(user_id),
    created_at TIMESTAMP
);

CREATE TABLE purchase_order_items (
    po_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT REFERENCES purchase_orders(purchase_order_id),
    purchase_request_item_id BIGINT REFERENCES purchase_request_items(purchase_request_item_id),
    product_id BIGINT REFERENCES products(product_id),
    ordered_quantity NUMERIC(18, 4) NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    line_total NUMERIC(14, 2)
);

CREATE TABLE goods_receipts (
    receipt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_code VARCHAR(50) UNIQUE NOT NULL,
    purchase_order_id BIGINT REFERENCES purchase_orders(purchase_order_id),
    received_by BIGINT REFERENCES user_accounts(user_id),
    status VARCHAR(30) DEFAULT 'RECEIVED',
    received_at TIMESTAMP,
    note TEXT
);

CREATE TABLE goods_receipt_items (
    receipt_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id BIGINT REFERENCES goods_receipts(receipt_id),
    po_item_id BIGINT REFERENCES purchase_order_items(po_item_id),
    inventory_movement_id BIGINT REFERENCES inventory_movements(movement_id),
    received_quantity NUMERIC(18, 4) NOT NULL,
    accepted_quantity NUMERIC(18, 4) DEFAULT 0,
    rejected_quantity NUMERIC(18, 4) DEFAULT 0,
    inspection_status VARCHAR(30) DEFAULT 'PENDING',
    inspected_by BIGINT REFERENCES user_accounts(user_id),
    inspection_note TEXT,
    inspected_at TIMESTAMP
);
